name: Build Static Node.js

on:
  workflow_dispatch:
    inputs:
      nodeVersion:
        description: 'Node.js version'
        required: true
        default: '22.15.0'
      ndkVersion:
        description: 'NDK version'
        required: true
        default: '27.2.12479018'
      arch:
        description: 'Arch'
        required: true
        default: 'arm64'
      sdkPlatform:
        description: 'SDK platform'
        required: true
        default: '35'
      configureOptions:
        description: 'Configure options'
        required: false
        default: '--without-inspector --fully-static --with-intl=full-icu --partly-static --shared-zlib=no --shared-openssl=no'

jobs:
  build:
    name: Build Static
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Fetch Node.js ${{ github.event.inputs.nodeVersion }}
      run: |
        curl -sOL "https://github.com/nodejs/node/archive/refs/tags/v${{ github.event.inputs.nodeVersion }}.zip"
        unzip -d . "v${{ github.event.inputs.nodeVersion }}.zip" >/dev/null

    - name: Prepare ICU Source
      run: |
        mkdir -p node-${{ github.event.inputs.nodeVersion }}/deps/icu
        curl -sOL https://github.com/unicode-org/icu/releases/download/release-75-1/icu4c-75_1-src.tgz
        tar xzf icu4c-75_1-src.tgz -C node-${{ github.event.inputs.nodeVersion }}/deps/icu

    - name: Patch Node.js
      working-directory: node-${{ github.event.inputs.nodeVersion }}
      run: |
        patch -p0 < ../android-configure.patch
        patch -p0 < ../zlib.patch

    - name: Cache Build Output
      uses: actions/cache@v4
      with:
        path: |
          node-${{ github.event.inputs.nodeVersion }}/out/Release
          node-${{ github.event.inputs.nodeVersion }}/deps/openssl
        key: static-build-${{ runner.os }}-${{ github.event.inputs.nodeVersion }}-${{ github.event.inputs.arch }}

    - name: Configure
      working-directory: node-${{ github.event.inputs.nodeVersion }}
      env:
        CC_host: gcc
        CXX_host: g++
        AR_host: ar
        CFLAGS: "-static"
        CXXFLAGS: "-static"
        LDFLAGS: "-static -Wl,--whole-archive -lpthread -Wl,--no-whole-archive"
      run: |
        chmod +x ./android-configure
        ./android-configure "$ANDROID_HOME/ndk/${{ github.event.inputs.ndkVersion }}" \
          "${{ github.event.inputs.sdkPlatform }}" \
          "${{ github.event.inputs.arch }}" \
          ${{ github.event.inputs.configureOptions }}

    - name: Build Static Library
      working-directory: node-${{ github.event.inputs.nodeVersion }}
      run: |
        make -j$(getconf _NPROCESSORS_ONLN) V=1 \
          LINK=$${CXX} \
          LD=$${CXX} \
          LDFLAGS="$${LDFLAGS} -static-libstdc++"

    - name: Collect Artifacts
      working-directory: node-${{ github.event.inputs.nodeVersion }}
      run: |
        mkdir -p ../build/{lib,include}
        find ./out/Release -name "*.a" -exec cp {} ../build/lib \;
        cp deps/openssl/openssl/libssl.a ../build/lib/
        cp deps/openssl/openssl/libcrypto.a ../build/lib/
        cp deps/zlib/libz.a ../build/lib/
        cp src/node.h ../build/include/
        cp -r deps/uv/include ../build/

    - uses: actions/upload-artifact@v4
      with:
        name: node-static-lib
        path: |
          ./build
        retention-days: 7
